<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200826125947 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE refactory_oauth_domain_model_app (persistence_object_identifier VARCHAR(40) NOT NULL, provider VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, clientid VARCHAR(255) NOT NULL, secret VARCHAR(255) NOT NULL, scope VARCHAR(255) NOT NULL, notes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', authorizationid VARCHAR(255) NOT NULL, apiuri VARCHAR(255) NOT NULL, INDEX IDX_FB98A21692C4739C (provider), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refactory_oauth_domain_model_provider (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, authenticationendpoint VARCHAR(255) NOT NULL, oauthclient VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_refactory_oauth_domain_model_provider (oauthclient), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE refactory_oauth_domain_model_app ADD CONSTRAINT FK_FB98A21692C4739C FOREIGN KEY (provider) REFERENCES refactory_oauth_domain_model_provider (persistence_object_identifier)');
        $this->addSql('ALTER TABLE neos_contentrepository_domain_model_nodedata DROP INDEX IDX_CE6515692D45FE4D, ADD UNIQUE INDEX UNIQ_CE6515692D45FE4D (movedto)');
        $this->addSql('DROP INDEX path ON neos_contentrepository_domain_model_nodedata');
        $this->addSql('CREATE INDEX pathindex ON neos_contentrepository_domain_model_nodedata (path(255))');
        $this->addSql('ALTER TABLE neos_media_domain_model_tag DROP FOREIGN KEY FK_CA4889693D8E604F');
        $this->addSql('ALTER TABLE neos_media_domain_model_tag ADD CONSTRAINT FK_CA4889693D8E604F FOREIGN KEY (parent) REFERENCES neos_media_domain_model_tag (persistence_object_identifier) ON DELETE SET NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE refactory_oauth_domain_model_app DROP FOREIGN KEY FK_FB98A21692C4739C');
        $this->addSql('DROP TABLE refactory_oauth_domain_model_app');
        $this->addSql('DROP TABLE refactory_oauth_domain_model_provider');
        $this->addSql('ALTER TABLE neos_contentrepository_domain_model_nodedata DROP INDEX UNIQ_CE6515692D45FE4D, ADD INDEX IDX_CE6515692D45FE4D (movedto)');
        $this->addSql('DROP INDEX pathindex ON neos_contentrepository_domain_model_nodedata');
        $this->addSql('CREATE INDEX path ON neos_contentrepository_domain_model_nodedata (path(255))');
        $this->addSql('ALTER TABLE neos_media_domain_model_tag DROP FOREIGN KEY FK_CA4889693D8E604F');
        $this->addSql('ALTER TABLE neos_media_domain_model_tag ADD CONSTRAINT FK_CA4889693D8E604F FOREIGN KEY (parent) REFERENCES neos_media_domain_model_tag (persistence_object_identifier)');
    }
}